-- Query plan guides
SELECT * 
FROM sys.plan_guides
WHERE name IN('PG_MyQuery2_ParameterizationForced',
              'PG_MyQuery2_Selective');

-- Drop plan guides
EXEC sp_control_plan_guide N'DROP', N'PG_MyQuery2_ParameterizationForced';
EXEC sp_control_plan_guide N'DROP', N'PG_MyQuery2_Selective';

--plan_guide_id name                                                                                                                             create_date             modify_date             is_disabled query_text                                                                                                                                                                                                                                                       scope_type scope_type_desc                                              scope_object_id scope_batch                                                                                                                                                                                                                                                      parameters                                                                                                                                                                                                                                                       hints
--------------- -------------------------------------------------------------------------------------------------------------------------------- ----------------------- ----------------------- ----------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ---------- ------------------------------------------------------------ --------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--65540         PG_MyQuery2_ParameterizationForced                                                                                               2023-06-24 19:34:08.380 2023-06-24 19:34:08.380 0           select orderid , custid , empid , orderdate from Sales . Orders where orderdate > = @0                                                                                                                                                                           3          TEMPLATE                                                     NULL            select orderid , custid , empid , orderdate from Sales . Orders where orderdate > = @0                                                                                                                                                                           @0 varchar(8000)                                                                                                                                                                                                                                                 OPTION(PARAMETERIZATION FORCED)
--65542         PG_MyQuery2_Selective                                                                                                            2023-06-24 19:34:08.390 2023-06-24 19:34:08.390 0           select orderid , custid , empid , orderdate from Sales . Orders where orderdate > = @0                                                                                                                                                                           2          SQL                                                          NULL            select orderid , custid , empid , orderdate from Sales . Orders where orderdate > = @0                                                                                                                                                                           @0 varchar(8000)                                                                                                                                                                                                                                                 OPTION(OPTIMIZE FOR (@0 = '99991231'))

--(2 rows affected)