---------------------------------------------------------------------
-- Concatenating Variables
---------------------------------------------------------------------

-- Concatenating Variables
-- DECLARE
--   @sql1 AS VARCHAR(8000),
--   @sql2 AS VARCHAR(8000),
--   @sql3 AS VARCHAR(8000);

-- SET @sql1 = <part 1>;
-- SET @sql2 = <part 2>;
-- SET @sql3 = <part 3>;

-- EXEC(@sql1 + @sql2 + @sql3);
-- GO

/*
------ ------ ------
Part 1 Part 2 Part 3
*/

-- Use MAX types instead
DECLARE @sql AS VARCHAR(MAX) = 
  'PRINT ''This output was generated by'
    + REPLICATE(CAST('.' AS VARCHAR(MAX)), 100000) + ''''
    + CHAR(13) + CHAR(10)
    + 'PRINT ''a long batch.''';
EXEC(@sql);

SELECT LEN(@sql) AS batch_length;
GO

--batch_length
----------------------
--100059