---------------------------------------------------------------------
-- Statement Limit
---------------------------------------------------------------------

-- In 2008 can use NVARCHAR(MAX)
DECLARE @sql AS NVARCHAR(MAX) = 
  N'PRINT ''This output was generated by'
    + REPLICATE(CAST(N'.' AS NVARCHAR(MAX)), 100000) + ''''
    + NCHAR(13) + NCHAR(10)
    + N'PRINT ''a long batch.''';
EXEC sp_executesql @sql;

SELECT LEN(@sql) AS batch_length;
GO

--This output was generated by.............
--a long batch.
--batch_length
----------------------
--100059